export const TOGGLE_CHECKBOX = "TOGGLE_CHECKBOX";
export const STORE_CHECKED_ITEM_DATA = "STORE_CHECKED_ITEM_DATA";
export const TOGGLE_PROFILE_VISIBILITY = "TOGGLE_PROFILE_VISIBILITY";
export const SET_USER = "SET_USER";
